version: '2'
services:
    shakti-app:
        image: shakti
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://shakti-postgresql:5432/shakti
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shakti-postgresql:
        extends:
            file: postgresql.yml
            service: shakti-postgresql
